version: '3'

services:

  db:
    image: mysql/mysql-server
    container_name: mySql
    environment:
      - MYSQL_ROOT_PASSWORD=my-password
      - MYSQL_DATABASE=charity
      - MYSQL_USER=user
      - MYSQL_PASSWORD=coders
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always

  charity:
    build:
      context: .
    #    image: registry.hub.docker.com/rainowy/charity
    container_name: charity
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      WAIT_HOSTS:  mySql:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mySql:3306/charity?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: coders
      #      AWS S3
      aws.s3.bucket: ${AWS_BUCKET}
      aws.access.key: ${AWS_ACCESS_KEY}
      aws.secret.key: ${AWS_SECRET_KEY}
      #       Mail
      spring.mail.host: smtp.gmail.com
      spring.mail.port: 587
      spring.mail.username: ${MAIL_USER}
      spring.mail.password: ${MAIL_PASS}


  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080


